version: '3.3'

services:
  mysql:
    image: mysql:8.0.16
    restart: always
    environment:
    - MYSQL_USER=clamaud
    - MYSQL_PASSWORD=voltaire
    - MYSQL_ROOT_PASSWORD=example
    - MYSQL_DATABASE=compta
    ports:
    - '3306:3306'
    volumes:
    - mysql-compta:/var/lib/mysql

volumes:
  mysql-compta:


