---

- name: Install Git - Zsh.
  package:
    name: "{{ git_package }}"
    state: "{{ git_package_state }}"
  with_items:
    - { package: "{{ git_package }}", state: "{{ git_package_state }}" }
    - { package: "{{ zsh_package }}", state: "{{ zsh_package_state }}" }
- name: Create Clamaud directory
  file:
    path: /home/clamaud
    state: directory
- name: Create Dump directory
  file:
    path: /home/clamaud/db-dump
    state: directory
- name: Create Compta directory
  file:
    path: /home/clamaud/Compta
    state: directory
- name: Copy Dump to folder
  copy:
    src: /home/clamaud/Documents/Projets/db-dump/backup.sql
    dest: /home/clamaud/db-dump/backup.sql
    owner: root
    group: root
    mode: '0777'
- git:
    repo: 'https://github.com/LAMAUD/Compta.git'
    dest: /home/clamaud/Compta
    version: develop
