---


- name: First Perso playbook
  hosts: multi
  vars_files:
    - vars.yml
  become: true
  handlers:
  - include: handlers/handlers.yml
  pre_tasks:
  - name: Message
    debug:
      msg: "La variable env_name est {{env_name}} et j'ai accès à la variable {{name_var}}"
  tasks:
  - include: tasks/common.yml
  roles:
  - role: geerlingguy.docker
