---


- name: First Perso playbook
  hosts: ansible-local-01
  vars_files:
    - vars.yml
  become: true
  handlers:
  - include: handlers/handlers.yml
  pre_tasks:
  - name: Message
    debug:
      msg: "La variable env_name est {{env_name}} et j'ai accès à la variable {{name_var}} et {{ansible_ssh_user}}"
  roles:
    - geerlingguy.docker
  tasks:
  - include: tasks/common.yml
